idb/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.contrib import admin

from tastypie.api import Api
from idb.resources import ImageResource, PlatformResource, DeveloperResource, GameResource

admin.autodiscover()
v1_api = Api(api_name='v1')
v1_api.register(ImageResource())
v1_api.register(PlatformResource())
v1_api.register(DeveloperResource())
v1_api.register(GameResource())

urlpatterns = patterns('',
    url(r'^$', 'idb.views.home', name='home'),
    url(r'^developer/', include(patterns('',
        url(r'^$', 'idb.views.developers', name='developers'),
        url(r'^(?P<developer_id>\d+)/$', 'idb.views.developer', name='developer'),
    ))),
    url(r'^platform/', include(patterns('',
        url(r'^$', 'idb.views.platforms', name='platforms'),
        url(r'^(?P<platform_id>\d+)/$', 'idb.views.platform', name='platform'),
    ))),
    url(r'^game/', include(patterns('',
        url(r'^$', 'idb.views.games', name='games'),
        url(r'^(?P<game_id>\d+)/$', 'idb.views.game', name='game'),
    ))),
    url(r'^search/', 'idb.views.search', name='search'),
    url(r'^dynamic/', TemplateView.as_view(template_name="dynamic.html")),
    url(r'^queries/','idb.views.queries', name="queries.html"),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(v1_api.urls)),
)

idb/models.py
import datetime

from django.db import models




class Image(models.Model):
    '''
    Image link

    @type description: models.CharField(255)
    @cvar description: Description of the image
    @type link: models.CharField(255)
    @cvar link: URL to the image
    '''
    description = models.CharField(max_length=255)
    link = models.CharField(max_length=255)

    def __unicode__(self):
        return self.description

    class Meta:
        ordering = ['description']
        verbose_name_plural = "Images'"


class Platform(models.Model):
    '''
    Platform Model that represents a video game platform

    @type name: models.CharField(255)
    @cvar name: Name of the platform
    @type manufacturer: models.CharField(255)
    @cvar manufacturer: the manufacturer of the platform
    @type release_date: models.DateField()
    @cvar release_date: date the platform was released
    @type media_format: models.Charfield(255)
    @cvar media_format: the form(s) of media (CDs, cartridge, etc) used by platform
    @type generation: models.SmallIntegerField()
    @cvar generation: the console generation of the platform
    @type youtube_link: models.CharField(255)
    @cvar youtube_link: link to a youtube video
    '''
    name = models.CharField(max_length=255)
    manufacturer = models.CharField(max_length=255)
    release_date = models.DateField('release date')
    media_format = models.CharField(max_length=255)
    generation = models.SmallIntegerField()
    youtube_link = models.CharField(max_length=255)
    twitter_link = models.CharField(max_length=255)

    images = models.ManyToManyField(Image)
    

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Platforms"


class Developer(models.Model):
    '''
    Developer Model that represents a video game developer

    @type name: models.CharField(255)
    @cvar name: Name of the developer
    @type date_founded: models.DateField()
    @cvar date_founded: date the developer studio was founded
    @type num_employees: models.SmallIntegerField()
    @cvar num_employees: the number of employees currently working at the studio
    @type status: models.CharField(255)
    @cvar status: the current state of the studio, active or defunct
    @type address: models.CharField(255)
    @cvar address: the address of the developer's HQ
    @type map_link: models.CharField(511)
    @cvar map_link: link to the Google Map of the address
    '''
    name = models.CharField(max_length=255)
    date_founded = models.DateField('date established')
    num_employees = models.IntegerField()
    status = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    map_link = models.CharField(max_length=511)
    
    platforms = models.ManyToManyField(Platform)
    images = models.ManyToManyField(Image)


    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = "Developers"


class Game(models.Model):
    '''
    Game Model that represents a video game

    @type title: models.CharField(255)
    @cvar title: Title of the game
    @type release_date: models.DateField()
    @cvar release_date: date the game was released
    @type genre: models.CharField(255)
    @cvar genre: genre of the game
    @type publisher: models.CharField(255)
    @cvar publisher: the publisher firm that released this game
    @type esrb_rating: models.CharField(255)
    @cvar esrb_rating: the offical ESRB rating
    @type youtube_link: models.CharField(255)
    @cvar youtube_link: link to a youtube video
    '''
    title = models.CharField(max_length=255)
    release_date = models.DateField('release date')
    genre = models.CharField(max_length=255)
    publisher = models.CharField(max_length=255)
    esrb_rating = models.CharField(max_length=255)
    youtube_link = models.CharField(max_length=255)
    
    developer = models.ForeignKey(Developer)
    platforms = models.ManyToManyField(Platform)
    images = models.ManyToManyField(Image)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name_plural = "Games"

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" {% block ng-html %}{% endblock ng-html %}>
<head>
    <title>{% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link rel="shortcut icon" href='{% static "favicon.ico" %}'/>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/app.css' %}" rel="stylesheet">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block head_extension %}
    {% endblock head_extension %}
</head>

<body {% block ng-body %}{% endblock ng-body %}>
    <nav class="navbar navbar-default container" role="navigation">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">IVGDb</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="{% block navbar_home %}{% endblock %}"><a href="/">Home</a></li>
                    <li class="{% block navbar_developer %}{% endblock %}"><a href="/developer/">Developer</a></li>
                    <li class="{% block navbar_platform %}{% endblock %}"><a href="/platform/">Platforms</a></li>
                    <li class="{% block navbar_game %}{% endblock %}"><a href="/game/">Games</a></li>
                    <li class="{% block navbar_queries %}{% endblock %}"><a href="/queries/">Queries</a></li>
		    <li class="{% block navbar_dynamic %}{% endblock %}"><a href="/dynamic/">Dynamic</a></li>
                </ul>
                <form class="navbar-form navbar-right" role="search" action={% url 'search' %}>
                    <div class="form-group">
                    {% if query %}
                        <input name="query" type="text" class="form-control" placeholder="{{ query }}">
                        {% else %}
                        <input name="query" type="text" class="form-control" placeholder="Search">
                    {% endif %}
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    {% block content %}
        my base content
    {% endblock content %}

    <footer class="container">
        <p style="color: #666666; padding-bottom: 15px; margin-top: 30px">
            &copy; <script>document.write(new Date().getFullYear())</script>
        </p>
    </footer>
</body>

</html>

templates/developer.html
{% extends 'base.html' %}

{% block navbar_developer %} active {% endblock %}

{% block title %}
IVGDb &middot; Developer | {{ developer.name }}
{% endblock title %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><h1>{{ developer.name }}</h1></div>
        <div class="panel-body">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    {% for i in developer.images.all %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
                    {% endfor %}
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    {% for i in developer.images.all %}
                        <div class="item{% if forloop.first %} active{% endif %}">
                            <img src={{ i.link }} alt="{{ i.description }}">
                            <div class="carousel-caption"> 
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>

    <!-- List group -->
    <ul class="list-group">
        <li class="list-group-item"><b>Founded:</b> {{ developer.date_founded }}</li>
        <li class="list-group-item"><b>Number of Employees:</b> {{ developer.num_employees }}</li>
        <li class="list-group-item"><b>Status:</b> {{ developer.status }}</li>
        <li class="list-group-item"><b>Platform(s):</b> 
            {% for p in developer.platforms.all %}
            <a href="/platform/{{ p.pk }}/">{{ p.name }}</a>{% if not forloop.last %},  {% endif %}
            {% endfor %}
        </li>
        <li class="list-group-item"><b>Game(s):</b> 
            {% for g in developer.game_set.all %}
            <a href="/game/{{ g.pk }}/">{{ g.title }}</a>{% if not forloop.last %},  {% endif %}
            {% endfor %}
        </li>
        <div class="row">
            <div class="col-md-6">
                <li class="list-group-item">
                <b>Address:</b> {{developer.address}}<br /><br />
                    {% if "" != developer.map_link %}
                        <div class="media-container">
                            <iframe frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src={{developer.map_link}}></iframe><br />
                        </div>
                    {% endif %}
                </li>
            </div>
        </div>
    </ul>
    </div>
</div>
{% endblock content %}

templates/developers.html
{% extends 'base.html' %}

{% block navbar_developer %} active {% endblock %}

{% block title %}
IVGDb &middot; Developers
{% endblock title %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading"><h1>Developers</h1></div>
        <div class="panel-body" align="center">
            {% for k in developer_dict %}
                <a href="#{{k}}">{{k}}</a>
                {% if not forloop.last %}
                 - 
                {% endif %}
            {% endfor %}
        </div>
        <ul class="list-group">
            {% for k, v in developer_dict.items %}
                <a id="{{k}}" class="list-group-item active">{{k}}</a>
                {% for d in v %}
                    <li class="list-group-item">
                        <img src="{{d.images.first.link}}" height="50" width="50" />
                        <a href="/developer/{{d.pk}}">{{d.name}}</a>
                    </li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

templates/dynamic.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block ng-html %}
ng-app="myApp"
{% endblock ng-html %}

{% block navbar_dynamic %} active {% endblock %}

{% block title %}
IVGDb &middot; Dynamic
{% endblock title %}

{% block head_extension %}
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static "css/angular.css" %}" rel="stylesheet">
{% endblock head_extension %}

{% block ng-body %}
ng-controller="MyCtrl1" style="background: #222222"
{% endblock ng-body %}

{% block content %}
<div class="container">
  <div class="well">
    <h1 class="text-info">Dynamic IVGDb</h1>
    <h4>Real-time content filtering</h4>
  </div>
  <tabset  justified="true">
    <tab heading="Games">
      <h3 id="games">Games</h3>
      <div class="row">
        <div class="col-md-10">
          <table class="table table-striped">
            <tr class="active">
              <th class="text-info">Title</th>
              <th class="text-info">Publisher</th>
              <th class="text-info">Genre</th>
              <th class="text-info">Release Date</th>
            </tr>
            <tr ng-repeat="game in games | filter:{title:game_query} | filter:{genre:genre}:exactCompare | orderBy:gameOrderProp">
              {% verbatim %}
              <td><a href="/game/{{ game.id }}">{{game.title}}</a></td>
              <td>{{game.publisher}}</td>
              <td>{{game.genre}}</td>
              <td>{{game.release_date}}</td>
              {% endverbatim %}
            </tr>
          </table>
        </div>
        <div class="col-md-2">
          <!--Sidebar content-->
         <div class="input-group">
           <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
           <input type="search" class="form-control input-sm" ng-model="game_query">
         </div>
          <select style="margin-top: 10px" class="form-control" ng-model="gameOrderProp">
            <option value="title">Alphabetical</option>
            <option value="-release_date">Newest</option>
            <option value="release_date">Oldest</option>
            <option value="publisher">Publisher</option>
          </select>
          <select style="margin-top: 10px" class="form-control" ng-model="genre">
            <option value="">All Genres</option>
            {% verbatim %}
            <option ng-repeat="g in getGenres()" value="{{ g }}">{{ g }}</option>
            {% endverbatim %}
          </select>
        </div>
      </div>
    </tab>
    <tab heading="Platforms">
      <h3 id="platforms">Platforms</h3>
      <div class="row">
        <div class="col-md-10">
          <table class="table table-striped">
            <tr class="active">
              <th class="text-info">Name</th>
              <th class="text-info">Manufacturer</th>
              <th class="text-info">Generation</th>
              <th class="text-info">Release Date</th>
            </tr>
            <tr ng-repeat="platform in platforms | filter:{name:platform_query} | filter:manufacturer | orderBy:platformOrderProp">
              {% verbatim %}
              <td><a href="/platform/{{ platform.id }}">{{platform.name}}</a></td>
              <td>{{platform.manufacturer}}</td>
              <td>{{platform.generation}}</td>
              <td>{{platform.release_date}}</td>
              {% endverbatim %}
            </tr>
          </table>
        </div>
        <div class="col-md-2">
          <!--Sidebar content-->
         <div class="input-group">
           <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
           <input type="search" class="form-control input-sm" ng-model="platform_query">
         </div>
          <select style="margin-top: 10px" class="form-control" ng-model="platformOrderProp">
            <option value="name">Alphabetical</option>
            <option value="-release_date">Newest</option>
            <option value="release_date">Oldest</option>
          </select>
          <select style="margin-top: 10px" class="form-control" ng-model="manufacturer">
            <option value="">All Manufacturers</option>
            {% verbatim %}
            <option ng-repeat="m in getManufacturers()" value="{{ m }}">{{ m }}</option>
            {% endverbatim %}
          </select>
        </div>
      </div>
    </tab>
    <tab heading="Developers">
      <h3 id="developers">Developers</h3>
      <div class="row">
        <div class="col-md-10">
          <table class="table table-striped">
            <tr class="active">
              <th class="text-info">Name</th>
              <th class="text-info">Number of Employees</th>
              <th class="text-info">Status</th>
              <th class="text-info">Date Founded</th>
            </tr>
            <tr ng-repeat="developer in developers | filter:{name:developer_query} | orderBy:developerOrderProp">
              {% verbatim %}
              <td><a href="/developer/{{ developer.id }}">{{developer.name}}</a></td>
              <td>{{developer.num_employees}}</td>
              <td>{{developer.status}}</td>
              <td>{{developer.date_founded}}</td>
              {% endverbatim %}
            </tr>
          </table>
        </div>
        <div class="col-md-2">
          <!--Sidebar content-->
         <div class="input-group">
           <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
           <input type="search" class="form-control input-sm" ng-model="developer_query">
         </div>
          <select style="margin-top: 10px" class="form-control" ng-model="developerOrderProp">
            <option value="name">Alphabetical</option>
            <option value="-date_founded">Newest</option>
            <option value="date_founded">Oldest</option>
            <option value="-num_employees">Size</option>
          </select>
        </div>
      </div>
    </tab>
  </tabset>


</div>

<!-- In production use:
<script src="//ajax.googleapis.com/ajax/libs/angularjs/x.x.x/angular.min.js"></script>
-->
<script src="{% static "js/angular.js" %}"></script>
<script src="{% static "js/angular-route.js" %}"></script>
<script src="{% static "js/ui-bootstrap-tpls.min.js" %}"></script>
<script src="{% static "js/app.js" %}"></script>
<script src="{% static "js/services.js" %}"></script>
<script src="{% static "js/controllers.js" %}"></script>
<script src="{% static "js/filters.js" %}"></script>
<script src="{% static "js/directives.js" %}"></script>
{% endblock content %}

templates/game.html
{% extends 'base.html' %}

{% block navbar_game %} active {% endblock %}

{% block title %}
IVGDb &middot; Game | {{ game.title }}
{% endblock title %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><h1>{{ game.title }}</h1></div>
        <div class="panel-body">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    {% for i in game.images.all %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
                    {% endfor %}
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    {% for i in game.images.all %}
                        <div class="item{% if forloop.first %} active{% endif %}">
                            <img src={{ i.link }} alt="{{ i.description }}">
                            <div class="carousel-caption"> 
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>

        <!-- List group -->
        <ul class="list-group">
            <li class="list-group-item"><b>Publisher:</b> {{ game.publisher }}</li>
            <li class="list-group-item"><b>US Release Date:</b> {{ game.release_date }}</li>
            <li class="list-group-item"><b>ESRB Rating:</b> {{ game.esrb_rating }}</li>
            <li class="list-group-item"><b>Genre:</b> {{ game.genre }}</li>
            <li class="list-group-item"><b>Developed by:</b> <a href="/developer/{{ game.developer.pk }}/">{{ game.developer.name }}</a></li>
            <li class="list-group-item"><b>Platform(s):</b>
                {% for p in game.platforms.all %}
                    <a href="/platform/{{ p.pk }}/">{{ p.name }}</a>{% if not forloop.last %},  {% endif %}
                {% endfor %}
            </li>
            <div class="row">
                <div class="col-md-6">
                    <li class="list-group-item" style="text-align: center">
                        <div class="media-container">
                            <iframe src=//{{game.youtube_link}} frameborder="0" allowfullscreen></iframe>
                        </div>
                    </li>
                </div>
            </div>
        </ul>
    </div>
</div>
{% endblock content %}

templates/games.html
{% extends 'base.html' %}

{% block navbar_game %} active {% endblock %}

{% block title %}
IVGDb &middot; Games
{% endblock title %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading"><h1>Games</h1></div>
        <div class="panel-body" align="center">
            {% for k in game_dict %}
                <a href="#{{k}}">{{k}}</a>
                {% if not forloop.last %}
                 - 
                {% endif %}
            {% endfor %}
        </div>
        <ul class="list-group">
            {% for k, v in game_dict.items %}
                <a id="{{k}}" class="list-group-item active">{{k}}</a>
                {% for g in v %}
                    <li class="list-group-item">
                        <img src="{{g.images.first.link}}" height="50" width="50" />
                        <a href="/game/{{g.pk}}">{{g.title}}</a>
                    </li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block navbar_home %} active {% endblock %}

{% block title %}
IVGDb &middot; Home
{% endblock title %}

{% block content %}
<div class="container jumbotron">
    <h1>IVGDb</h1>
    <p>The Internet Video Game Database</p>
    <p><a class="btn btn-primary" role="button" href="http://www.cs.utexas.edu/users/downing/cs373/drupal/idb3/" target="_blank">Learn more</a></p>
    <p style="color:#707070; font-size: 110%; margin-top: 30px">By <strong>The Pirates of Silicon Valley</strong> 
    

    (<a href="http://www.linkedin.com/pub/noah-cho/47/264/726">Noah Cho</a>, 
    <a href="http://www.linkedin.com/in/cristhianescobar/">Cristhian Escobar</a>, 
    <a href="http://www.linkedin.com/pub/arash-ghoreyshi/47/685/a4a">Arash Ghoreyshi</a>, 
    <a href="http://www.linkedin.com/pub/doug-goldstein/49/373/976">Doug Goldstein</a>, 
    <a href="http://www.linkedin.com/pub/robert-hammond/79/14b/b96">Robert Hammond</a>, 
    and 
    <a href="http://www.linkedin.com/pub/richard-lage/63/794/853">Richard Lage</a>)  
    
    </p>
</div>
<div class="container jumbotron">
    <div class="row" >
        <ul style="list-style-type: none">
            <div class="col-sm-4">
                <li>
                    <h2>Developers</h2>
                       <ul style="list-style-type: none; margin-left: -30px">
                        {% for d in developer_list %}
                            <li><a href="/developer/{{ d.pk }}">{{d.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </div>
            <div class="col-sm-4">
                <li>
                    <h2>Platforms</h2>
                    <ul style="list-style-type: none; margin-left: -30px">
                        {% for p in platform_list %}
                            <li><a href="/platform/{{ p.pk }}">{{p.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </div>
            <div class="col-sm-4">
                <li>
                    <h2>Games</h2>
                    <ul style="list-style-type: none; margin-left: -30px">
                        {% for g in game_list %}
                            <li><a href="/game/{{ g.pk }}">{{g.title}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </div>
        </ul>
    </div>
</div>
{% endblock content %}

templates/platform.html
{% extends 'base.html' %}

{% block navbar_platform %} active {% endblock %}

{% block title %}
IVGDb &middot; Platform | {{ platform.name }}
{% endblock title %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading"><h1>{{ platform.name }}</h1></div>
        <div class="panel-body">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    {% for i in platform.images.all %}
                        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
                    {% endfor %}
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    {% for i in platform.images.all %}
                        <div class="item{% if forloop.first %} active{% endif %}">
                            <img src={{ i.link }} alt="{{ i.description }}">
                            <div class="carousel-caption"> 
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>

        <!-- List group -->
        <ul class="list-group">
            <li class="list-group-item"><b>Manufacturer:</b> {{ platform.manufacturer }}</li>
            <li class="list-group-item"><b>US Release Date:</b> {{ platform.release_date }}</li>
            <li class="list-group-item"><b>Media:</b> {{ platform.media_format }}</li>
            <li class="list-group-item"><b>Generation:</b> {{ platform.generation }}</li>
            <li class="list-group-item"><b>Developer(s): </b> 
                {% for d in platform.developer_set.all %}
                    <a href="/developer/{{ d.pk }}/">{{ d.name }}</a>{% if not forloop.last %},  {% endif %}
                {% endfor %}
            </li>
            <li class="list-group-item"><b>Game(s):</b> 
                {% for g in platform.game_set.all %}
                    <a href="/game/{{ g.pk }}/">{{ g.title }}</a>{% if not forloop.last %},  {% endif %}
                {% endfor %}
            </li>
            <div class="row">
                <div class="col-md-6">
                    <li class="list-group-item">
                    <div class="media-container">
                        <iframe src="//{{ platform.youtube_link }}" frameborder="0" allowfullscreen></iframe>
                    </div>
                </li>
                </div>
                <div class="col-md-6">
                    <li class="list-group-item">
                        <a class="twitter-timeline" data-dnt="true" href="" data-widget-id="{{ platform.twitter_link }}"></a>
                        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                    </li>
                </div>
            </div>
        </ul>
    </div>
</div>
{% endblock content %}

templates/platforms.html
{% extends 'base.html' %}

{% block navbar_platform %} active {% endblock %}

{% block title %}
IVGDb &middot; Platforms
{% endblock title %}

{% block content %}
<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading"><h1>Platforms</h1></div>
        <div class="panel-body" align="center">
            {% for k in platform_dict %}
                <a href="#{{k}}">{{k}}</a>
                {% if not forloop.last %}
                 - 
                {% endif %}
            {% endfor %}
        </div>
        <ul class="list-group">
            {% for k, v in platform_dict.items %}
                <a id="{{k}}" class="list-group-item active">{{k}}</a>
                {% for p in v %}
                    <li class="list-group-item">
                        <img src="{{p.images.first.link}}" height="50" width="50" />
                        <a href="/platform/{{p.pk}}">{{p.name}}</a>
                    </li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}